// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDShihGdc1EbSNFMuENCDJFnBZIDuNJ3EE',
    appId: '1:332840344309:web:cf76b1a792682281b183bc',
    messagingSenderId: '332840344309',
    projectId: 'customplans-41d82',
    authDomain: 'customplans-41d82.firebaseapp.com',
    storageBucket: 'customplans-41d82.firebasestorage.app',
    measurementId: 'G-NMXX3YBXWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDvZHrJ7cJdXuFxEyZO_zc94sgi4jJEQ',
    appId: '1:332840344309:android:bbbb76cbe5e7c72fb183bc',
    messagingSenderId: '332840344309',
    projectId: 'customplans-41d82',
    storageBucket: 'customplans-41d82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ZiaB74YUfdcEqxC2-tsqkCVGBAK6t0M',
    appId: '1:332840344309:ios:2af77c052c64d661b183bc',
    messagingSenderId: '332840344309',
    projectId: 'customplans-41d82',
    storageBucket: 'customplans-41d82.firebasestorage.app',
    iosBundleId: 'com.example.verve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ZiaB74YUfdcEqxC2-tsqkCVGBAK6t0M',
    appId: '1:332840344309:ios:2af77c052c64d661b183bc',
    messagingSenderId: '332840344309',
    projectId: 'customplans-41d82',
    storageBucket: 'customplans-41d82.firebasestorage.app',
    iosBundleId: 'com.example.verve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDShihGdc1EbSNFMuENCDJFnBZIDuNJ3EE',
    appId: '1:332840344309:web:f6c81965a11a2d0fb183bc',
    messagingSenderId: '332840344309',
    projectId: 'customplans-41d82',
    authDomain: 'customplans-41d82.firebaseapp.com',
    storageBucket: 'customplans-41d82.firebasestorage.app',
    measurementId: 'G-QS6DXS1R3E',
  );
}
